/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateCourseRequest = IDL.Record({
  'code' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'weeklyHours' : IDL.Nat,
  'departmentId' : IDL.Nat,
});
export const CreateDepartmentRequest = IDL.Record({
  'hodUserId' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
});
export const RoomType = IDL.Variant({
  'lab' : IDL.Null,
  'seminar' : IDL.Null,
  'lecture' : IDL.Null,
});
export const CreateRoomRequest = IDL.Record({
  'name' : IDL.Text,
  'capacity' : IDL.Nat,
  'roomType' : RoomType,
});
export const Department = IDL.Record({
  'id' : IDL.Nat,
  'hodUserId' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
});
export const Room = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'capacity' : IDL.Nat,
  'roomType' : RoomType,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'departmentId' : IDL.Opt(IDL.Nat),
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'weeklyHours' : IDL.Nat,
  'teacherId' : IDL.Opt(IDL.Principal),
  'departmentId' : IDL.Nat,
});
export const Day = IDL.Variant({
  'fri' : IDL.Null,
  'mon' : IDL.Null,
  'sat' : IDL.Null,
  'thu' : IDL.Null,
  'tue' : IDL.Null,
  'wed' : IDL.Null,
});
export const Period = IDL.Variant({
  'p1' : IDL.Null,
  'p2' : IDL.Null,
  'p3' : IDL.Null,
  'p4' : IDL.Null,
  'p5' : IDL.Null,
  'p6' : IDL.Null,
  'p7' : IDL.Null,
  'p8' : IDL.Null,
});
export const TimetableEntry = IDL.Record({
  'id' : IDL.Nat,
  'day' : Day,
  'period' : Period,
  'teacherId' : IDL.Opt(IDL.Principal),
  'roomId' : IDL.Nat,
  'courseId' : IDL.Nat,
  'departmentId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignTeacherToCourse' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'createCourse' : IDL.Func([CreateCourseRequest], [], []),
  'createDepartment' : IDL.Func([CreateDepartmentRequest], [], []),
  'createRoom' : IDL.Func([CreateRoomRequest], [], []),
  'getAllDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
  'getAllRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoursesByDepartment' : IDL.Func([IDL.Nat], [IDL.Vec(Course)], ['query']),
  'getCoursesByTeacher' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Course)],
      ['query'],
    ),
  'getTimetableByDepartment' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TimetableEntry)],
      ['query'],
    ),
  'getTimetableByTeacher' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TimetableEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateCourseRequest = IDL.Record({
    'code' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'weeklyHours' : IDL.Nat,
    'departmentId' : IDL.Nat,
  });
  const CreateDepartmentRequest = IDL.Record({
    'hodUserId' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
  });
  const RoomType = IDL.Variant({
    'lab' : IDL.Null,
    'seminar' : IDL.Null,
    'lecture' : IDL.Null,
  });
  const CreateRoomRequest = IDL.Record({
    'name' : IDL.Text,
    'capacity' : IDL.Nat,
    'roomType' : RoomType,
  });
  const Department = IDL.Record({
    'id' : IDL.Nat,
    'hodUserId' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
  });
  const Room = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'capacity' : IDL.Nat,
    'roomType' : RoomType,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'departmentId' : IDL.Opt(IDL.Nat),
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'weeklyHours' : IDL.Nat,
    'teacherId' : IDL.Opt(IDL.Principal),
    'departmentId' : IDL.Nat,
  });
  const Day = IDL.Variant({
    'fri' : IDL.Null,
    'mon' : IDL.Null,
    'sat' : IDL.Null,
    'thu' : IDL.Null,
    'tue' : IDL.Null,
    'wed' : IDL.Null,
  });
  const Period = IDL.Variant({
    'p1' : IDL.Null,
    'p2' : IDL.Null,
    'p3' : IDL.Null,
    'p4' : IDL.Null,
    'p5' : IDL.Null,
    'p6' : IDL.Null,
    'p7' : IDL.Null,
    'p8' : IDL.Null,
  });
  const TimetableEntry = IDL.Record({
    'id' : IDL.Nat,
    'day' : Day,
    'period' : Period,
    'teacherId' : IDL.Opt(IDL.Principal),
    'roomId' : IDL.Nat,
    'courseId' : IDL.Nat,
    'departmentId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignTeacherToCourse' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'createCourse' : IDL.Func([CreateCourseRequest], [], []),
    'createDepartment' : IDL.Func([CreateDepartmentRequest], [], []),
    'createRoom' : IDL.Func([CreateRoomRequest], [], []),
    'getAllDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
    'getAllRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoursesByDepartment' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Course)],
        ['query'],
      ),
    'getCoursesByTeacher' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Course)],
        ['query'],
      ),
    'getTimetableByDepartment' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TimetableEntry)],
        ['query'],
      ),
    'getTimetableByTeacher' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TimetableEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };