/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : bigint,
  'code' : string,
  'name' : string,
  'color' : string,
  'weeklyHours' : bigint,
  'teacherId' : [] | [Principal],
  'departmentId' : bigint,
}
export interface CreateCourseRequest {
  'code' : string,
  'name' : string,
  'color' : string,
  'weeklyHours' : bigint,
  'departmentId' : bigint,
}
export interface CreateDepartmentRequest {
  'hodUserId' : [] | [Principal],
  'name' : string,
}
export interface CreateRoomRequest {
  'name' : string,
  'capacity' : bigint,
  'roomType' : RoomType,
}
export type Day = { 'fri' : null } |
  { 'mon' : null } |
  { 'sat' : null } |
  { 'thu' : null } |
  { 'tue' : null } |
  { 'wed' : null };
export interface Department {
  'id' : bigint,
  'hodUserId' : [] | [Principal],
  'name' : string,
}
export type Period = { 'p1' : null } |
  { 'p2' : null } |
  { 'p3' : null } |
  { 'p4' : null } |
  { 'p5' : null } |
  { 'p6' : null } |
  { 'p7' : null } |
  { 'p8' : null };
export interface Room {
  'id' : bigint,
  'name' : string,
  'capacity' : bigint,
  'roomType' : RoomType,
}
export type RoomType = { 'lab' : null } |
  { 'seminar' : null } |
  { 'lecture' : null };
export interface TimetableEntry {
  'id' : bigint,
  'day' : Day,
  'period' : Period,
  'teacherId' : [] | [Principal],
  'roomId' : bigint,
  'courseId' : bigint,
  'departmentId' : bigint,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
  'departmentId' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignTeacherToCourse' : ActorMethod<[bigint, Principal], undefined>,
  'createCourse' : ActorMethod<[CreateCourseRequest], undefined>,
  'createDepartment' : ActorMethod<[CreateDepartmentRequest], undefined>,
  'createRoom' : ActorMethod<[CreateRoomRequest], undefined>,
  'getAllDepartments' : ActorMethod<[], Array<Department>>,
  'getAllRooms' : ActorMethod<[], Array<Room>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoursesByDepartment' : ActorMethod<[bigint], Array<Course>>,
  'getCoursesByTeacher' : ActorMethod<[Principal], Array<Course>>,
  'getTimetableByDepartment' : ActorMethod<[bigint], Array<TimetableEntry>>,
  'getTimetableByTeacher' : ActorMethod<[Principal], Array<TimetableEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];