/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Department {
    id: bigint;
    hodUserId?: Principal;
    name: string;
}
export interface CreateDepartmentRequest {
    hodUserId?: Principal;
    name: string;
}
export interface CreateRoomRequest {
    name: string;
    capacity: bigint;
    roomType: RoomType;
}
export interface CreateCourseRequest {
    code: string;
    name: string;
    color: string;
    weeklyHours: bigint;
    departmentId: bigint;
}
export interface TimetableEntry {
    id: bigint;
    day: Day;
    period: Period;
    teacherId?: Principal;
    roomId: bigint;
    courseId: bigint;
    departmentId: bigint;
}
export interface Room {
    id: bigint;
    name: string;
    capacity: bigint;
    roomType: RoomType;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
    departmentId?: bigint;
}
export interface Course {
    id: bigint;
    code: string;
    name: string;
    color: string;
    weeklyHours: bigint;
    teacherId?: Principal;
    departmentId: bigint;
}
export enum Day {
    fri = "fri",
    mon = "mon",
    sat = "sat",
    thu = "thu",
    tue = "tue",
    wed = "wed"
}
export enum Period {
    p1 = "p1",
    p2 = "p2",
    p3 = "p3",
    p4 = "p4",
    p5 = "p5",
    p6 = "p6",
    p7 = "p7",
    p8 = "p8"
}
export enum RoomType {
    lab = "lab",
    seminar = "seminar",
    lecture = "lecture"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignTeacherToCourse(courseId: bigint, teacherId: Principal): Promise<void>;
    createCourse(request: CreateCourseRequest): Promise<void>;
    createDepartment(request: CreateDepartmentRequest): Promise<void>;
    createRoom(request: CreateRoomRequest): Promise<void>;
    getAllDepartments(): Promise<Array<Department>>;
    getAllRooms(): Promise<Array<Room>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoursesByDepartment(departmentId: bigint): Promise<Array<Course>>;
    getCoursesByTeacher(teacherId: Principal): Promise<Array<Course>>;
    getTimetableByDepartment(departmentId: bigint): Promise<Array<TimetableEntry>>;
    getTimetableByTeacher(teacherId: Principal): Promise<Array<TimetableEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { Course as _Course, CreateDepartmentRequest as _CreateDepartmentRequest, CreateRoomRequest as _CreateRoomRequest, Day as _Day, Department as _Department, Period as _Period, Room as _Room, RoomType as _RoomType, TimetableEntry as _TimetableEntry, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignTeacherToCourse(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignTeacherToCourse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignTeacherToCourse(arg0, arg1);
            return result;
        }
    }
    async createCourse(arg0: CreateCourseRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(arg0);
            return result;
        }
    }
    async createDepartment(arg0: CreateDepartmentRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDepartment(to_candid_CreateDepartmentRequest_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDepartment(to_candid_CreateDepartmentRequest_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createRoom(arg0: CreateRoomRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoom(to_candid_CreateRoomRequest_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoom(to_candid_CreateRoomRequest_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllDepartments(): Promise<Array<Department>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDepartments();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDepartments();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRooms(): Promise<Array<Room>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRooms();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRooms();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoursesByDepartment(arg0: bigint): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesByDepartment(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesByDepartment(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoursesByTeacher(arg0: Principal): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesByTeacher(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesByTeacher(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimetableByDepartment(arg0: bigint): Promise<Array<TimetableEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimetableByDepartment(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimetableByDepartment(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimetableByTeacher(arg0: Principal): Promise<Array<TimetableEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimetableByTeacher(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimetableByTeacher(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Course_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Course): Course {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Day_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Day): Day {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Department_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Department): Department {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Period_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Period): Period {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_RoomType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomType): RoomType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Room_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Room): Room {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_TimetableEntry_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimetableEntry): TimetableEntry {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    hodUserId: [] | [Principal];
    name: string;
}): {
    id: bigint;
    hodUserId?: Principal;
    name: string;
} {
    return {
        id: value.id,
        hodUserId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.hodUserId)),
        name: value.name
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    capacity: bigint;
    roomType: _RoomType;
}): {
    id: bigint;
    name: string;
    capacity: bigint;
    roomType: RoomType;
} {
    return {
        id: value.id,
        name: value.name,
        capacity: value.capacity,
        roomType: from_candid_RoomType_n16(_uploadFile, _downloadFile, value.roomType)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    email: string;
    departmentId: [] | [bigint];
}): {
    name: string;
    role: string;
    email: string;
    departmentId?: bigint;
} {
    return {
        name: value.name,
        role: value.role,
        email: value.email,
        departmentId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.departmentId))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    code: string;
    name: string;
    color: string;
    weeklyHours: bigint;
    teacherId: [] | [Principal];
    departmentId: bigint;
}): {
    id: bigint;
    code: string;
    name: string;
    color: string;
    weeklyHours: bigint;
    teacherId?: Principal;
    departmentId: bigint;
} {
    return {
        id: value.id,
        code: value.code,
        name: value.name,
        color: value.color,
        weeklyHours: value.weeklyHours,
        teacherId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.teacherId)),
        departmentId: value.departmentId
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    day: _Day;
    period: _Period;
    teacherId: [] | [Principal];
    roomId: bigint;
    courseId: bigint;
    departmentId: bigint;
}): {
    id: bigint;
    day: Day;
    period: Period;
    teacherId?: Principal;
    roomId: bigint;
    courseId: bigint;
    departmentId: bigint;
} {
    return {
        id: value.id,
        day: from_candid_Day_n30(_uploadFile, _downloadFile, value.day),
        period: from_candid_Period_n32(_uploadFile, _downloadFile, value.period),
        teacherId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.teacherId)),
        roomId: value.roomId,
        courseId: value.courseId,
        departmentId: value.departmentId
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lab: null;
} | {
    seminar: null;
} | {
    lecture: null;
}): RoomType {
    return "lab" in value ? RoomType.lab : "seminar" in value ? RoomType.seminar : "lecture" in value ? RoomType.lecture : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fri: null;
} | {
    mon: null;
} | {
    sat: null;
} | {
    thu: null;
} | {
    tue: null;
} | {
    wed: null;
}): Day {
    return "fri" in value ? Day.fri : "mon" in value ? Day.mon : "sat" in value ? Day.sat : "thu" in value ? Day.thu : "tue" in value ? Day.tue : "wed" in value ? Day.wed : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    p1: null;
} | {
    p2: null;
} | {
    p3: null;
} | {
    p4: null;
} | {
    p5: null;
} | {
    p6: null;
} | {
    p7: null;
} | {
    p8: null;
}): Period {
    return "p1" in value ? Period.p1 : "p2" in value ? Period.p2 : "p3" in value ? Period.p3 : "p4" in value ? Period.p4 : "p5" in value ? Period.p5 : "p6" in value ? Period.p6 : "p7" in value ? Period.p7 : "p8" in value ? Period.p8 : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Room>): Array<Room> {
    return value.map((x)=>from_candid_Room_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Course>): Array<Course> {
    return value.map((x)=>from_candid_Course_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TimetableEntry>): Array<TimetableEntry> {
    return value.map((x)=>from_candid_TimetableEntry_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Department>): Array<Department> {
    return value.map((x)=>from_candid_Department_n10(_uploadFile, _downloadFile, x));
}
function to_candid_CreateDepartmentRequest_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateDepartmentRequest): _CreateDepartmentRequest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreateRoomRequest_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateRoomRequest): _CreateRoomRequest {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_RoomType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): _RoomType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    email: string;
    departmentId?: bigint;
}): {
    name: string;
    role: string;
    email: string;
    departmentId: [] | [bigint];
} {
    return {
        name: value.name,
        role: value.role,
        email: value.email,
        departmentId: value.departmentId ? candid_some(value.departmentId) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hodUserId?: Principal;
    name: string;
}): {
    hodUserId: [] | [Principal];
    name: string;
} {
    return {
        hodUserId: value.hodUserId ? candid_some(value.hodUserId) : candid_none(),
        name: value.name
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    capacity: bigint;
    roomType: RoomType;
}): {
    name: string;
    capacity: bigint;
    roomType: _RoomType;
} {
    return {
        name: value.name,
        capacity: value.capacity,
        roomType: to_candid_RoomType_n7(_uploadFile, _downloadFile, value.roomType)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): {
    lab: null;
} | {
    seminar: null;
} | {
    lecture: null;
} {
    return value == RoomType.lab ? {
        lab: null
    } : value == RoomType.seminar ? {
        seminar: null
    } : value == RoomType.lecture ? {
        lecture: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
